services:
  mysql-credit-card:
    image: mysql:latest
    restart: always
    container_name: mysql-credit-card
    hostname: "mysql-credit-card"
    environment:
      MYSQL_DATABASE: 'creditcarddb'
      MYSQL_USER: 'user_mysql'
      MYSQL_PASSWORD: 'mSq@2024*PtEc'
      MYSQL_ROOT_PASSWORD: 'mSq@2024*PtEc'
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-credit-card" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - my_network


  mscreditcard:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql-credit-card:
        condition: service_healthy
    hostname: "ms-credit-card"
    environment:
      MYSQL_HOSTNAME: mysql-credit-card
    ports:
      - 8080:8080
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    external: true